# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: housing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='housing.proto',
  package='housing',
  syntax='proto3',
  serialized_pb=_b('\n\rhousing.proto\x12\x07housing\"n\n\x14\x45stimatePriceRequest\x12\x16\n\x0e\x66rom_timestamp\x18\x01 \x01(\x03\x12\x14\n\x0cto_timestamp\x18\x02 \x01(\x03\x12\x17\n\x0fprice_in_pounds\x18\x03 \x01(\x05\x12\x0f\n\x07\x62orough\x18\x04 \x01(\t\"}\n\x15\x45stimatePriceResponse\x12*\n\x05\x65rror\x18\x01 \x01(\x0e\x32\x1b.housing.EstimatePriceError\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12!\n\x19\x65stimated_price_in_pounds\x18\x03 \x01(\x05*\xf8\x01\n\x12\x45stimatePriceError\x12\x0c\n\x08NO_ERROR\x10\x00\x12\x1a\n\x16MISSING_FROM_TIMESTAMP\x10\x01\x12\x18\n\x14MISSING_TO_TIMESTAMP\x10\x02\x12\x1b\n\x17MISSING_PRICE_IN_POUNDS\x10\x03\x12\x13\n\x0fMISSING_BOROUGH\x10\x04\x12\x15\n\x11\x42OROUGH_NOT_FOUND\x10\x05\x12\x1c\n\x18\x46ROM_TIMESTAMP_NOT_FOUND\x10\x06\x12\x1a\n\x16TO_TIMESTAMP_NOT_FOUND\x10\x07\x12\x1b\n\x17TIMESTAMPS_OUT_OF_ORDER\x10\x08\x32[\n\x07Housing\x12P\n\rEstimatePrice\x12\x1d.housing.EstimatePriceRequest\x1a\x1e.housing.EstimatePriceResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ESTIMATEPRICEERROR = _descriptor.EnumDescriptor(
  name='EstimatePriceError',
  full_name='housing.EstimatePriceError',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSING_FROM_TIMESTAMP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSING_TO_TIMESTAMP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSING_PRICE_IN_POUNDS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSING_BOROUGH', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOROUGH_NOT_FOUND', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FROM_TIMESTAMP_NOT_FOUND', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TO_TIMESTAMP_NOT_FOUND', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TIMESTAMPS_OUT_OF_ORDER', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=266,
  serialized_end=514,
)
_sym_db.RegisterEnumDescriptor(_ESTIMATEPRICEERROR)

EstimatePriceError = enum_type_wrapper.EnumTypeWrapper(_ESTIMATEPRICEERROR)
NO_ERROR = 0
MISSING_FROM_TIMESTAMP = 1
MISSING_TO_TIMESTAMP = 2
MISSING_PRICE_IN_POUNDS = 3
MISSING_BOROUGH = 4
BOROUGH_NOT_FOUND = 5
FROM_TIMESTAMP_NOT_FOUND = 6
TO_TIMESTAMP_NOT_FOUND = 7
TIMESTAMPS_OUT_OF_ORDER = 8



_ESTIMATEPRICEREQUEST = _descriptor.Descriptor(
  name='EstimatePriceRequest',
  full_name='housing.EstimatePriceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_timestamp', full_name='housing.EstimatePriceRequest.from_timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_timestamp', full_name='housing.EstimatePriceRequest.to_timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price_in_pounds', full_name='housing.EstimatePriceRequest.price_in_pounds', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='borough', full_name='housing.EstimatePriceRequest.borough', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=136,
)


_ESTIMATEPRICERESPONSE = _descriptor.Descriptor(
  name='EstimatePriceResponse',
  full_name='housing.EstimatePriceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='housing.EstimatePriceResponse.error', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='housing.EstimatePriceResponse.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='estimated_price_in_pounds', full_name='housing.EstimatePriceResponse.estimated_price_in_pounds', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=263,
)

_ESTIMATEPRICERESPONSE.fields_by_name['error'].enum_type = _ESTIMATEPRICEERROR
DESCRIPTOR.message_types_by_name['EstimatePriceRequest'] = _ESTIMATEPRICEREQUEST
DESCRIPTOR.message_types_by_name['EstimatePriceResponse'] = _ESTIMATEPRICERESPONSE
DESCRIPTOR.enum_types_by_name['EstimatePriceError'] = _ESTIMATEPRICEERROR

EstimatePriceRequest = _reflection.GeneratedProtocolMessageType('EstimatePriceRequest', (_message.Message,), dict(
  DESCRIPTOR = _ESTIMATEPRICEREQUEST,
  __module__ = 'housing_pb2'
  # @@protoc_insertion_point(class_scope:housing.EstimatePriceRequest)
  ))
_sym_db.RegisterMessage(EstimatePriceRequest)

EstimatePriceResponse = _reflection.GeneratedProtocolMessageType('EstimatePriceResponse', (_message.Message,), dict(
  DESCRIPTOR = _ESTIMATEPRICERESPONSE,
  __module__ = 'housing_pb2'
  # @@protoc_insertion_point(class_scope:housing.EstimatePriceResponse)
  ))
_sym_db.RegisterMessage(EstimatePriceResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class HousingStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.EstimatePrice = channel.unary_unary(
          '/housing.Housing/EstimatePrice',
          request_serializer=EstimatePriceRequest.SerializeToString,
          response_deserializer=EstimatePriceResponse.FromString,
          )


  class HousingServicer(object):

    def EstimatePrice(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_HousingServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'EstimatePrice': grpc.unary_unary_rpc_method_handler(
            servicer.EstimatePrice,
            request_deserializer=EstimatePriceRequest.FromString,
            response_serializer=EstimatePriceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'housing.Housing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaHousingServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def EstimatePrice(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaHousingStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def EstimatePrice(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    EstimatePrice.future = None


  def beta_create_Housing_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('housing.Housing', 'EstimatePrice'): EstimatePriceRequest.FromString,
    }
    response_serializers = {
      ('housing.Housing', 'EstimatePrice'): EstimatePriceResponse.SerializeToString,
    }
    method_implementations = {
      ('housing.Housing', 'EstimatePrice'): face_utilities.unary_unary_inline(servicer.EstimatePrice),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Housing_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('housing.Housing', 'EstimatePrice'): EstimatePriceRequest.SerializeToString,
    }
    response_deserializers = {
      ('housing.Housing', 'EstimatePrice'): EstimatePriceResponse.FromString,
    }
    cardinalities = {
      'EstimatePrice': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'housing.Housing', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
